# Generated by Django 5.2.8 on 2026-03-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Register', 'verbose_name_plural': 'Register'},
        ),
    ]
